// bom-diff-export.ts — format a diffBoms() result as markdown.
//
// Output prioritizes Claude Code readability: markdown tables with
// right-aligned numerics, changes grouped by kind (Added / Removed /
// Qty changes / Price changes), unchanged rows collapsed to a single
// summary line so a pasted diff isn't padded with hundreds of no-op
// rows. Header carries both runs' pipelines + job_ids so the reader
// (human or LLM) can tell what was compared without opening the SPA.

import type { BomRunDetail } from "./api-hooks";
import type { DiffResult, DiffRow, AggregatedLine } from "./bom-diff";

// ─── Formatters ────────────────────────────────────────────────────

function fmtMoney(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "—";
  const sign = n < 0 ? "-" : "";
  const abs = Math.abs(n).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return `${sign}$${abs}`;
}

function fmtDeltaMoney(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "—";
  if (Math.abs(n) < 0.005) return "$0.00";
  const sign = n > 0 ? "+" : "-";
  const abs = Math.abs(n).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return `${sign}$${abs}`;
}

function fmtPct(delta: number, base: number): string {
  if (!Number.isFinite(base) || Math.abs(base) < 0.005) return "";
  const pct = (delta / base) * 100;
  const sign = pct > 0 ? "+" : "";
  return `(${sign}${pct.toFixed(1)}%)`;
}

function fmtQty(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "—";
  if (Number.isInteger(n)) return String(n);
  return n.toFixed(2);
}

function fmtDeltaQty(n: number | null | undefined): string {
  if (n == null || !Number.isFinite(n)) return "—";
  if (Math.abs(n) < 0.005) return "0";
  const sign = n > 0 ? "+" : "";
  return `${sign}${fmtQty(n)}`;
}

// Markdown table cells can't contain pipes; escape defensively.
function md(s: string | null | undefined): string {
  if (s == null) return "—";
  return String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function truncate(s: string, max = 80): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + "…";
}

// ─── Row extractors ────────────────────────────────────────────────

interface Side {
  qty: number;
  totalCost: number;
  totalPrice: number;
  unit: string | null;
  section: string | null;
}

function sideFrom(a: AggregatedLine | null): Side | null {
  if (!a) return null;
  return {
    qty:        a.quantity,
    totalCost:  a.total_cost,
    totalPrice: a.total_price,
    unit:       a.unit,
    section:    a.section,
  };
}

// ─── Public API ────────────────────────────────────────────────────

interface RunMeta {
  id?: number | null;
  job_id?: string | null;
  client_id?: string | null;
  output_mode?: string | null;
  generated_at?: string | null;
  source_pipeline?: string | null;
  item_count?: number | null;
  total_cost?: number | null;
  total_price?: number | null;
}

function metaFromRun(detail: BomRunDetail | null | undefined): RunMeta {
  if (!detail) return {};
  const gen = detail.generated_bom ?? ({} as any);
  return {
    id:              detail.id,
    job_id:          detail.job_id ?? gen.job_id,
    client_id:       detail.client_id ?? gen.client_id,
    output_mode:     detail.output_mode ?? gen.output_mode,
    generated_at:    detail.created_at ?? gen.generated_at,
    source_pipeline: gen.source_pipeline ?? null,
    item_count:      gen.item_count ?? gen.line_items?.length ?? null,
    total_cost:      gen.totals?.total_cost ?? null,
    total_price:     gen.totals?.total_price ?? null,
  };
}

/**
 * Render a diffBoms() result as markdown, ready to paste into a
 * Claude Code conversation. Both runs' metadata sits at the top so
 * the reader can tell what was compared without needing the SPA.
 */
export function formatDiffAsMarkdown(
  diff: DiffResult,
  leftRun: BomRunDetail | null | undefined,
  rightRun: BomRunDetail | null | undefined,
): string {
  const L = metaFromRun(leftRun);
  const R = metaFromRun(rightRun);
  const s = diff.summary;

  const lines: string[] = [];

  lines.push("# BOM Run Diff");
  lines.push("");
  lines.push("Generated by Designer Desktop → Run Diff → Export.");
  lines.push("");

  // ── Metadata header ────────────────────────────────────────────
  lines.push("## Runs");
  lines.push("");
  lines.push("| | Left (baseline) | Right (compared) |");
  lines.push("|---|---|---|");
  lines.push(`| **Run ID** | ${L.id ?? "—"} | ${R.id ?? "—"} |`);
  lines.push(`| **Job ID** | ${md(L.job_id ?? null)} | ${md(R.job_id ?? null)} |`);
  lines.push(`| **Contractor** | ${md(L.client_id ?? null)} | ${md(R.client_id ?? null)} |`);
  lines.push(`| **Pipeline** | ${md(L.source_pipeline ?? "wrightsoft_xls")} | ${md(R.source_pipeline ?? "wrightsoft_xls")} |`);
  lines.push(`| **Output mode** | ${md(L.output_mode ?? null)} | ${md(R.output_mode ?? null)} |`);
  lines.push(`| **Generated at** | ${md(L.generated_at ?? null)} | ${md(R.generated_at ?? null)} |`);
  lines.push("");

  // ── Summary ────────────────────────────────────────────────────
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Left | Right | Δ |");
  lines.push("|---|---:|---:|---:|");
  lines.push(`| Line items | ${s.leftItemCount} | ${s.rightItemCount} | ${s.itemCountDelta > 0 ? "+" : ""}${s.itemCountDelta} |`);
  lines.push(
    `| Total cost | ${fmtMoney(s.leftTotalCost)} | ${fmtMoney(s.rightTotalCost)} | ` +
    `${fmtDeltaMoney(s.totalCostDelta)} ${fmtPct(s.totalCostDelta, s.leftTotalCost)} |`
  );
  lines.push(
    `| Total price | ${fmtMoney(s.leftTotalPrice)} | ${fmtMoney(s.rightTotalPrice)} | ` +
    `${fmtDeltaMoney(s.totalPriceDelta)} ${fmtPct(s.totalPriceDelta, s.leftTotalPrice)} |`
  );
  lines.push("");
  lines.push(
    `**Row-level counts:** Added ${s.addedCount} · Removed ${s.removedCount} · ` +
    `Changed ${s.changedCount} · Unchanged ${s.unchangedCount}`
  );
  lines.push("");

  // ── Group rows by change kind ──────────────────────────────────
  const added:      DiffRow[] = [];
  const removed:    DiffRow[] = [];
  const qtyChanged: DiffRow[] = [];
  const priceChanged: DiffRow[] = [];
  const otherChanged: DiffRow[] = [];
  let unchangedCount = 0;
  let unchangedLeftCost = 0;
  let unchangedRightCost = 0;
  for (const row of diff.rows) {
    switch (row.change) {
      case "added":         added.push(row); break;
      case "removed":       removed.push(row); break;
      case "qty_changed":   qtyChanged.push(row); break;
      case "price_changed": priceChanged.push(row); break;
      case "changed":       otherChanged.push(row); break;
      case "unchanged":
        unchangedCount++;
        unchangedLeftCost  += row.left?.total_cost  ?? 0;
        unchangedRightCost += row.right?.total_cost ?? 0;
        break;
    }
  }

  // ── Added ──────────────────────────────────────────────────────
  if (added.length > 0) {
    lines.push(`## Added (${added.length} rows) — present on Right only`);
    lines.push("");
    lines.push("| SKU | Description | Section | Qty | Unit | Total cost | Total price |");
    lines.push("|---|---|---|---:|---|---:|---:|");
    for (const row of added) {
      const r = row.right!;
      lines.push(
        `| ${md(row.key.startsWith("sku:") ? row.key.slice(4) : "—")} ` +
        `| ${md(truncate(row.label, 60))} ` +
        `| ${md(row.section)} ` +
        `| ${fmtQty(r.quantity)} ` +
        `| ${md(r.unit)} ` +
        `| ${fmtMoney(r.total_cost)} ` +
        `| ${fmtMoney(r.total_price)} |`
      );
    }
    lines.push("");
  }

  // ── Removed ────────────────────────────────────────────────────
  if (removed.length > 0) {
    lines.push(`## Removed (${removed.length} rows) — present on Left only`);
    lines.push("");
    lines.push("| SKU | Description | Section | Qty | Unit | Total cost | Total price |");
    lines.push("|---|---|---|---:|---|---:|---:|");
    for (const row of removed) {
      const l = row.left!;
      lines.push(
        `| ${md(row.key.startsWith("sku:") ? row.key.slice(4) : "—")} ` +
        `| ${md(truncate(row.label, 60))} ` +
        `| ${md(row.section)} ` +
        `| ${fmtQty(l.quantity)} ` +
        `| ${md(l.unit)} ` +
        `| ${fmtMoney(l.total_cost)} ` +
        `| ${fmtMoney(l.total_price)} |`
      );
    }
    lines.push("");
  }

  // ── Qty changed ────────────────────────────────────────────────
  if (qtyChanged.length > 0) {
    lines.push(`## Quantity changes (${qtyChanged.length} rows)`);
    lines.push("");
    lines.push("| SKU | Description | Left qty | Right qty | Δ qty | Δ total cost | Δ total price |");
    lines.push("|---|---|---:|---:|---:|---:|---:|");
    for (const row of qtyChanged) {
      lines.push(
        `| ${md(row.key.startsWith("sku:") ? row.key.slice(4) : "—")} ` +
        `| ${md(truncate(row.label, 60))} ` +
        `| ${fmtQty(row.left?.quantity)} ` +
        `| ${fmtQty(row.right?.quantity)} ` +
        `| ${fmtDeltaQty(row.qtyDelta)} ` +
        `| ${fmtDeltaMoney(row.totalCostDelta)} ` +
        `| ${fmtDeltaMoney(row.totalPriceDelta)} |`
      );
    }
    lines.push("");
  }

  // ── Price changed ──────────────────────────────────────────────
  if (priceChanged.length > 0) {
    lines.push(`## Price changes (${priceChanged.length} rows) — same qty, money moved`);
    lines.push("");
    lines.push("| SKU | Description | Qty | Left total cost | Right total cost | Δ cost | Δ price |");
    lines.push("|---|---|---:|---:|---:|---:|---:|");
    for (const row of priceChanged) {
      const qty = row.left?.quantity ?? row.right?.quantity ?? 0;
      lines.push(
        `| ${md(row.key.startsWith("sku:") ? row.key.slice(4) : "—")} ` +
        `| ${md(truncate(row.label, 60))} ` +
        `| ${fmtQty(qty)} ` +
        `| ${fmtMoney(row.left?.total_cost)} ` +
        `| ${fmtMoney(row.right?.total_cost)} ` +
        `| ${fmtDeltaMoney(row.totalCostDelta)} ` +
        `| ${fmtDeltaMoney(row.totalPriceDelta)} |`
      );
    }
    lines.push("");
  }

  // ── Other multi-field changes ──────────────────────────────────
  if (otherChanged.length > 0) {
    lines.push(`## Mixed changes (${otherChanged.length} rows) — qty and price both moved`);
    lines.push("");
    lines.push("| SKU | Description | Left qty | Right qty | Δ qty | Δ cost | Δ price |");
    lines.push("|---|---|---:|---:|---:|---:|---:|");
    for (const row of otherChanged) {
      lines.push(
        `| ${md(row.key.startsWith("sku:") ? row.key.slice(4) : "—")} ` +
        `| ${md(truncate(row.label, 60))} ` +
        `| ${fmtQty(row.left?.quantity)} ` +
        `| ${fmtQty(row.right?.quantity)} ` +
        `| ${fmtDeltaQty(row.qtyDelta)} ` +
        `| ${fmtDeltaMoney(row.totalCostDelta)} ` +
        `| ${fmtDeltaMoney(row.totalPriceDelta)} |`
      );
    }
    lines.push("");
  }

  // ── Unchanged collapse ────────────────────────────────────────
  if (unchangedCount > 0) {
    lines.push(`## Unchanged (${unchangedCount} rows) — collapsed`);
    lines.push("");
    lines.push(
      `Skipped ${unchangedCount} rows whose SKU, qty, cost, and price ` +
      `all matched (within $0.005 tolerance). ` +
      `Combined unchanged total cost: **${fmtMoney(unchangedLeftCost)}** (left) / ` +
      `**${fmtMoney(unchangedRightCost)}** (right).`
    );
    lines.push("");
  }

  return lines.join("\n");
}
