"""
ProCalcs Wrightsoft PDF Extractor — Source Identifier
Detects whether a PDF was generated by Wrightsoft Right-Suite Universal.
Part of the multi-software parser architecture.

ProCalcs HVAC Software — Phase 1 Validator
"""

import fitz  # PyMuPDF


def identify_source(pdf_path: str) -> dict:
    """
    Opens a PDF and checks for Wrightsoft fingerprints.
    Returns a dict with source info or None if not recognized.
    """
    doc = fitz.open(pdf_path)
    first_page_text = doc[0].get_text()
    doc.close()

    result = {
        "recognized": False,
        "source_software": "Unknown",
        "software_version": "",
        "calc_method": "",
    }

    # Check for Wrightsoft fingerprint
    if "Right-Suite" in first_page_text or "Right-J" in first_page_text:
        result["recognized"] = True
        result["source_software"] = "Wrightsoft Right-Suite Universal"

        # Extract version (pattern: "25.0.03" or similar after Right-Suite)
        import re
        version_match = re.search(
            r"Right-Suite.*?Universal\s+(\d{4})\s+([\d.]+)", first_page_text
        )
        if version_match:
            result["software_version"] = (
                f"{version_match.group(1)} {version_match.group(2)}"
            )

        # Check calc method
        if "MJ8" in first_page_text:
            result["calc_method"] = "Manual J 8th Edition"

    # Check for Elite RHVAC fingerprint
    elif "Elite" in first_page_text and "RHVAC" in first_page_text:
        result["recognized"] = True
        result["source_software"] = "Elite RHVAC"
        # TODO: Build Elite RHVAC extractor

    # Check for Cool Calc fingerprint
    elif "Cool Calc" in first_page_text or "CoolCalc" in first_page_text:
        result["recognized"] = True
        result["source_software"] = "Cool Calc"
        # TODO: Build Cool Calc extractor

    # Check for Conduit Tech fingerprint
    elif "Conduit" in first_page_text:
        result["recognized"] = True
        result["source_software"] = "Conduit Tech"
        # TODO: Build Conduit Tech extractor

    return result


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        info = identify_source(sys.argv[1])
        print(f"Recognized: {info['recognized']}")
        print(f"Software:   {info['source_software']}")
        print(f"Version:    {info['software_version']}")
        print(f"Calc Method:{info['calc_method']}")
    else:
        print("Usage: python source_identifier.py <path_to_pdf>")
