"""add bom_runs table for run history

Revision ID: 3661371ab0be
Revises: 370d0c3e9d5e
Create Date: 2026-05-15 14:40:13.168948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3661371ab0be'
down_revision = '370d0c3e9d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(length=255), nullable=True),
    sa.Column('source_rup_filename', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('output_mode', sa.String(length=50), nullable=True),
    sa.Column('parsed_design_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generated_bom', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('anthropic_duration_ms', sa.Integer(), nullable=True),
    sa.Column('anthropic_input_tokens', sa.Integer(), nullable=True),
    sa.Column('anthropic_output_tokens', sa.Integer(), nullable=True),
    sa.Column('bom_service_revision', sa.String(length=40), nullable=True),
    sa.Column('reviewer_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('regenerated_from_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['regenerated_from_id'], ['bom_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_runs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_runs_created_by_email'), ['created_by_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_runs_regenerated_from_id'), ['regenerated_from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_runs_reviewer_status'), ['reviewer_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bom_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_runs_reviewer_status'))
        batch_op.drop_index(batch_op.f('ix_bom_runs_regenerated_from_id'))
        batch_op.drop_index(batch_op.f('ix_bom_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_bom_runs_created_by_email'))
        batch_op.drop_index(batch_op.f('ix_bom_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_bom_runs_client_id'))

    op.drop_table('bom_runs')
    # ### end Alembic commands ###
