"""billing: users + subscription_events tables

Revision ID: 370d0c3e9d5e
Revises: 
Create Date: 2026-05-04 21:02:20.674725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370d0c3e9d5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('bom_count_total', sa.Integer(), nullable=False),
    sa.Column('bom_count_monthly', sa.Integer(), nullable=False),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_stripe_event_id'), ['stripe_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscription_events_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_stripe_event_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_event_type'))

    op.drop_table('subscription_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
