// Run History — diagnostic surface for the bom_runs persistence layer
// (procalcs-bom Phase 3) and the list/detail/review/regenerate API
// (Phase 4, commit 27990eb). Built for Richard's testing harness:
// scan recent BOM generations, jump into one to see what the parser +
// AI saw, mark it good / needs_fix / blocked with a note, and one-
// click regenerate to compare the output after a code change.
//
// Layout: master/detail in a single page. Left column = scrollable
// run list with filter chips (status + free-text q + client_id);
// right column = detail of the selected row with the review form,
// regenerate button, parsed_design_data + generated_bom previews.
//
// Re-uses the same envelope unwrapper (apiFetchEnvelope) all other
// catalog/profile/billing hooks use — see src/lib/api-hooks.ts.

import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { useQueryClient } from "@tanstack/react-query";
import {
  Beaker,
  CheckCircle2,
  CircleDashed,
  FileSpreadsheet,
  GitCompareArrows,
  Pencil,
  Tag,
  X,
  ListChecks,
  Loader2,
  RefreshCw,
  Search,
  Upload,
  Wrench,
  XCircle,
  Eye,
  Clock,
  Mail,
  Hash,
  RotateCcw,
} from "lucide-react";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { UserChip } from "@/components/user-chip";
import {
  useListBomRuns,
  useGetBomRun,
  useReviewBomRun,
  useRegenerateBomRun,
  useCompareBomRunFile,
  useUpdateBomRunTags,
  type BomRunSummary,
  type ReviewerStatus,
  type CompareReport,
  getListBomRunsQueryKey,
  getGetBomRunQueryKey,
} from "@/lib/api-hooks";

// ─── Status visuals ────────────────────────────────────────────────────

const STATUS_META: Record<ReviewerStatus, { label: string; variant: "secondary" | "default" | "destructive" | "outline"; icon: typeof CircleDashed }> = {
  unset:      { label: "Unset",      variant: "outline",     icon: CircleDashed },
  good:       { label: "Good",       variant: "default",     icon: CheckCircle2 },
  needs_fix:  { label: "Needs fix",  variant: "secondary",   icon: Wrench },
  blocked:    { label: "Blocked",    variant: "destructive", icon: XCircle },
};

const STATUS_OPTIONS: ReviewerStatus[] = ["unset", "good", "needs_fix", "blocked"];

function StatusBadge({ status }: { status: ReviewerStatus }) {
  const m = STATUS_META[status];
  const Icon = m.icon;
  return (
    <Badge variant={m.variant} className="gap-1 px-2">
      <Icon className="w-3 h-3" />
      {m.label}
    </Badge>
  );
}

// ─── Page ──────────────────────────────────────────────────────────────

export default function RunHistoryPage() {
  const [statusFilter, setStatusFilter] = useState<ReviewerStatus | "all">("all");
  const [clientFilter, setClientFilter] = useState<string>("");
  const [q, setQ] = useState<string>("");
  const [selectedId, setSelectedId] = useState<number | null>(null);

  // Debounce-free; the list endpoint is cheap (summary projection only)
  // and Richard types slowly enough that re-querying per keystroke is fine.
  const list = useListBomRuns({
    reviewer_status: statusFilter === "all" ? undefined : statusFilter,
    client_id: clientFilter.trim() || undefined,
    q: q.trim() || undefined,
    limit: 100,
  });

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto">
      <div>
        <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
          <ListChecks className="w-5 h-5 text-primary" />
          Run History
        </h1>
        <p className="text-muted-foreground text-sm mt-1 max-w-2xl">
          Every BOM generated by the staging stack lands here. Filter, open one to
          inspect what the parser + AI saw, mark it{" "}
          <span className="font-medium">good / needs_fix / blocked</span>, and one-click
          regenerate when you've shipped a fix.
        </p>
      </div>

      {/* Filter bar */}
      <Card>
        <CardContent className="p-4 flex flex-wrap gap-3 items-end">
          <div className="flex-1 min-w-[200px]">
            <Label htmlFor="q" className="text-xs uppercase tracking-wide text-muted-foreground">
              Search
            </Label>
            <div className="relative mt-1">
              <Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-muted-foreground" />
              <Input
                id="q"
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder="job_id or email…"
                className="pl-8 h-9"
              />
            </div>
          </div>
          <div className="min-w-[180px]">
            <Label htmlFor="client" className="text-xs uppercase tracking-wide text-muted-foreground">
              Client ID
            </Label>
            <Input
              id="client"
              value={clientFilter}
              onChange={(e) => setClientFilter(e.target.value)}
              placeholder="exact match"
              className="h-9 mt-1"
            />
          </div>
          <div className="min-w-[160px]">
            <Label className="text-xs uppercase tracking-wide text-muted-foreground">Status</Label>
            <Select
              value={statusFilter}
              onValueChange={(v) => setStatusFilter(v as ReviewerStatus | "all")}
            >
              <SelectTrigger className="h-9 mt-1">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All</SelectItem>
                {STATUS_OPTIONS.map((s) => (
                  <SelectItem key={s} value={s}>
                    {STATUS_META[s].label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => list.refetch()}
            disabled={list.isFetching}
          >
            {list.isFetching ? (
              <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            )}
            Refresh
          </Button>
        </CardContent>
      </Card>

      {/* Master / detail */}
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,420px),1fr] gap-6">
        <RunList
          loading={list.isPending}
          error={(list.error as any)?.error ?? null}
          rows={list.data?.runs ?? []}
          total={list.data?.total ?? 0}
          selectedId={selectedId}
          onSelect={setSelectedId}
        />
        <RunDetail
          runId={selectedId}
          onAfterReviewOrRegenerate={() => {
            // Invalidate both the list and the open detail so the UI
            // picks up the new state without manual refresh.
            list.refetch();
          }}
        />
      </div>
    </div>
  );
}

// ─── Run list ──────────────────────────────────────────────────────────

function RunList({
  loading,
  error,
  rows,
  total,
  selectedId,
  onSelect,
}: {
  loading: boolean;
  error: string | null;
  rows: BomRunSummary[];
  total: number;
  selectedId: number | null;
  onSelect: (id: number) => void;
}) {
  return (
    <Card className="overflow-hidden flex flex-col h-fit max-h-[calc(100vh-280px)]">
      <CardHeader className="py-3 flex-row items-center justify-between space-y-0">
        <div>
          <CardTitle className="text-sm">Runs</CardTitle>
          <CardDescription className="text-xs">
            {loading ? "Loading…" : `${rows.length} of ${total}`}
          </CardDescription>
        </div>
      </CardHeader>
      <Separator />
      <div className="overflow-y-auto">
        {error && (
          <div className="p-4 text-sm text-destructive">Failed to load: {error}</div>
        )}
        {!error && !loading && rows.length === 0 && (
          <div className="p-8 text-center text-sm text-muted-foreground">
            No runs match the current filters.
          </div>
        )}
        <ul className="divide-y divide-border/60">
          {rows.map((r) => (
            <li key={r.id}>
              <button
                onClick={() => onSelect(r.id)}
                className={cn(
                  "w-full text-left p-3 hover:bg-muted/40 transition-colors",
                  selectedId === r.id && "bg-primary/5 ring-1 ring-inset ring-primary/30",
                )}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <p className="font-medium truncate text-sm">{r.job_id}</p>
                    <p className="text-xs text-muted-foreground truncate">
                      {r.client_id} · {formatDate(r.created_at)}
                    </p>
                  </div>
                  <StatusBadge status={r.reviewer_status} />
                </div>
                <div className="flex items-center gap-3 mt-1.5 text-[11px] text-muted-foreground">
                  <UserChip email={r.created_by_email} />
                  <span className="flex items-center gap-1">
                    <Hash className="w-3 h-3" />
                    {r.id}
                  </span>
                  <span>
                    {r.item_count ?? 0} items
                  </span>
                  {r.total_price != null && (
                    <span>${r.total_price.toFixed(2)}</span>
                  )}
                  {r.regenerated_from_id != null && (
                    <span className="flex items-center gap-1" title={`Regenerated from #${r.regenerated_from_id}`}>
                      <RotateCcw className="w-3 h-3" />#{r.regenerated_from_id}
                    </span>
                  )}
                </div>
              </button>
            </li>
          ))}
        </ul>
        {loading && rows.length === 0 && (
          <div className="p-8 flex justify-center">
            <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
          </div>
        )}
      </div>
    </Card>
  );
}

// ─── Run detail ────────────────────────────────────────────────────────

function RunDetail({
  runId,
  onAfterReviewOrRegenerate,
}: {
  runId: number | null;
  onAfterReviewOrRegenerate: () => void;
}) {
  const detail = useGetBomRun(runId);
  const review = useReviewBomRun();
  const regen = useRegenerateBomRun();
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [, setLocation] = useLocation();

  // Local form state — initialized from the loaded record but free
  // to diverge until the user clicks Save.
  const [statusDraft, setStatusDraft] = useState<ReviewerStatus>("unset");
  const [notesDraft, setNotesDraft] = useState<string>("");
  // Tweak-and-regenerate dialog state. Must be declared BEFORE the
  // early-return guards below — adding a hook after an early return
  // breaks the Rules of Hooks (React error #310) when runId flips
  // from null to a value.
  const [tweakOpen, setTweakOpen] = useState(false);

  // Sync drafts when a different row loads.
  useEffect(() => {
    if (detail.data) {
      setStatusDraft(detail.data.reviewer_status);
      setNotesDraft(detail.data.reviewer_notes ?? "");
    }
  }, [detail.data?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  if (runId == null) {
    return (
      <Card className="flex items-center justify-center min-h-[300px]">
        <CardContent className="text-center space-y-2 p-8">
          <Eye className="w-8 h-8 mx-auto text-muted-foreground/50" />
          <p className="text-sm text-muted-foreground">Pick a run from the list.</p>
        </CardContent>
      </Card>
    );
  }

  if (detail.isPending) {
    return (
      <Card className="flex items-center justify-center min-h-[300px]">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </Card>
    );
  }

  if (detail.error) {
    return (
      <Card>
        <CardContent className="p-6 text-sm text-destructive">
          Failed to load run #{runId}: {(detail.error as any)?.error ?? "unknown error"}
        </CardContent>
      </Card>
    );
  }

  const run = detail.data!;
  const bom = run.generated_bom;

  const handleSave = () => {
    review.mutate(
      { id: run.id, status: statusDraft, notes: notesDraft },
      {
        onSuccess: () => {
          toast({ title: "Review saved", description: `Run #${run.id} → ${STATUS_META[statusDraft].label}` });
          queryClient.invalidateQueries({ queryKey: getGetBomRunQueryKey(run.id) });
          queryClient.invalidateQueries({ queryKey: ["bom-runs"] });
          onAfterReviewOrRegenerate();
        },
        onError: (err) => {
          toast({
            title: "Failed to save review",
            description: err?.error ?? "unknown error",
            variant: "destructive",
          });
        },
      },
    );
  };

  const handleRegenerate = (designOverride?: Record<string, any>) => {
    regen.mutate(
      { id: run.id, ...(designOverride ? { design_data: designOverride } : {}) },
      {
        onSuccess: (newBom) => {
          toast({
            title: designOverride ? "Tweak-regenerated" : "Regenerated",
            description: `New run #${(newBom as any).run_id} created from #${run.id}.`,
          });
          // Invalidate the list so the new row appears, and pull the
          // detail of the new run automatically by selecting it.
          queryClient.invalidateQueries({ queryKey: ["bom-runs"] });
          onAfterReviewOrRegenerate();
        },
        onError: (err) => {
          toast({
            title: "Regeneration failed",
            description: err?.error ?? "unknown error",
            variant: "destructive",
          });
        },
      },
    );
  };

  return (
    <div className="space-y-4">
      {/* Header card */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between gap-3 flex-wrap">
            <div>
              <CardTitle className="text-base flex items-center gap-2">
                <Hash className="w-4 h-4 text-muted-foreground" />
                Run #{run.id}
              </CardTitle>
              <CardDescription className="mt-0.5 break-all">{run.job_id}</CardDescription>
            </div>
            <StatusBadge status={run.reviewer_status} />
          </div>
        </CardHeader>
        <Separator />
        <CardContent className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 text-xs">
          <Stat label="Client" value={run.client_id} />
          <Stat label="Mode" value={run.output_mode ?? "—"} />
          <Stat label="Created" value={formatDate(run.created_at)} icon={Clock} />
          <Stat label="By" value={<UserChip email={run.created_by_email} size="md" />} />
          <Stat label="Items" value={String(run.item_count ?? 0)} />
          <Stat
            label="Total"
            value={run.total_price != null ? `$${run.total_price.toFixed(2)}` : "—"}
          />
          <Stat
            label="Catalog / Rules / AI"
            value={
              bom
                ? `${bom.catalog_match_item_count ?? 0} / ${bom.rules_engine_item_count ?? 0} / ${bom.ai_item_count ?? 0}`
                : "—"
            }
          />
          <Stat
            label="Parent"
            value={run.regenerated_from_id != null ? `#${run.regenerated_from_id}` : "—"}
          />
        </CardContent>
      </Card>

      {/* Reviewer form */}
      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Reviewer</CardTitle>
          <CardDescription className="text-xs">
            Mark this run for the regression suite. Notes carry forward — leaving
            them empty when re-flipping status preserves the previous note.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-1 sm:grid-cols-[200px,1fr] gap-3">
            <div>
              <Label className="text-xs">Status</Label>
              <Select value={statusDraft} onValueChange={(v) => setStatusDraft(v as ReviewerStatus)}>
                <SelectTrigger className="mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {STATUS_OPTIONS.map((s) => (
                    <SelectItem key={s} value={s}>
                      {STATUS_META[s].label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Notes</Label>
              <Textarea
                value={notesDraft}
                onChange={(e) => setNotesDraft(e.target.value)}
                placeholder="What's right / wrong about this run…"
                rows={3}
                className="mt-1"
              />
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-2 justify-between">
            <div className="text-xs text-muted-foreground">
              {run.reviewer_email ? (
                <span className="inline-flex items-center gap-1.5">
                  Last reviewed by <UserChip email={run.reviewer_email} showText={false} /> · {formatDate(run.reviewed_at)}
                </span>
              ) : (
                <>Not yet reviewed</>
              )}
            </div>
            <div className="flex gap-2 flex-wrap">
              {run.regenerated_from_id != null && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    setLocation(
                      `/diagnostics/run-diff?left=${run.regenerated_from_id}&right=${run.id}`,
                    )
                  }
                >
                  <GitCompareArrows className="w-3.5 h-3.5 mr-1.5" />
                  Diff with parent
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={() => setTweakOpen(true)}
                disabled={regen.isPending || !run.parsed_design_data}
                title={!run.parsed_design_data ? "No parsed_design_data on this run" : "Edit design_data and regenerate"}
              >
                <Pencil className="w-3.5 h-3.5 mr-1.5" />
                Tweak & regen
              </Button>
              <Button variant="outline" size="sm" onClick={() => handleRegenerate()} disabled={regen.isPending}>
                {regen.isPending ? (
                  <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                ) : (
                  <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
                )}
                Regenerate
              </Button>
              <Button size="sm" onClick={handleSave} disabled={review.isPending}>
                {review.isPending ? (
                  <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                ) : (
                  <CheckCircle2 className="w-3.5 h-3.5 mr-1.5" />
                )}
                Save review
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Generated BOM line items (compact) */}
      {bom && bom.line_items?.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <Beaker className="w-4 h-4 text-emerald-600" />
              Line items ({bom.line_items.length})
            </CardTitle>
          </CardHeader>
          <Separator />
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b bg-muted/30 text-muted-foreground">
                  <th className="text-left px-4 py-2 font-medium">Source</th>
                  <th className="text-left px-3 py-2 font-medium">SKU</th>
                  <th className="text-left px-3 py-2 font-medium">Description</th>
                  <th className="text-right px-3 py-2 font-medium">Qty</th>
                  <th className="text-right px-4 py-2 font-medium">Total</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/50">
                {bom.line_items.map((li, i) => (
                  <tr key={i} className="hover:bg-muted/20">
                    <td className="px-4 py-1.5 text-[10px] uppercase text-muted-foreground">
                      {li.source ?? "ai"}
                    </td>
                    <td className="px-3 py-1.5 font-mono text-[11px]">{li.sku ?? "—"}</td>
                    <td className="px-3 py-1.5">{li.description}</td>
                    <td className="px-3 py-1.5 text-right">{li.quantity} {li.unit}</td>
                    <td className="px-4 py-1.5 text-right font-semibold">
                      ${(li.total_price ?? li.total_cost ?? 0).toFixed(2)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      )}

      <TweakRegenDialog
        open={tweakOpen}
        onOpenChange={setTweakOpen}
        designData={run.parsed_design_data ?? {}}
        running={regen.isPending}
        onSubmit={(d) => {
          handleRegenerate(d);
          setTweakOpen(false);
        }}
      />

      {/* Tag chips — regression suite curation (Phase 9) */}
      <TagChipsCard runId={run.id} tags={run.tags} />

      {/* Compare against contractor's reference BOM */}
      <CompareCard runId={run.id} />

      {/* Raw payloads — collapsed-by-default JSON dumps for the deep dive */}
      <RawPayload label="parsed_design_data" payload={run.parsed_design_data} />
      <RawPayload label="generated_bom" payload={run.generated_bom} />
    </div>
  );
}

// ─── Tag chips card (Phase 9) ──────────────────────────────────────────

function TagChipsCard({ runId, tags }: { runId: number; tags: string[] }) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const update = useUpdateBomRunTags();
  const [draft, setDraft] = useState("");

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: getGetBomRunQueryKey(runId) });
    queryClient.invalidateQueries({ queryKey: ["bom-runs"] });
  };

  const apply = (op: "add" | "remove", tag: string) => {
    update.mutate(
      { id: runId, ...(op === "add" ? { add: [tag] } : { remove: [tag] }) },
      {
        onSuccess: () => {
          invalidate();
          if (op === "add") setDraft("");
        },
        onError: (err) =>
          toast({
            title: op === "add" ? "Tag rejected" : "Failed to remove tag",
            description: err?.error ?? "unknown error",
            variant: "destructive",
          }),
      },
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm flex items-center gap-2">
          <Tag className="w-4 h-4 text-muted-foreground" />
          Tags
        </CardTitle>
        <CardDescription className="text-xs">
          Group this run into a regression suite. Use lowercase / kebab-case
          (e.g. <span className="font-mono">regression-v1</span>,{" "}
          <span className="font-mono">edge-case</span>).
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="flex flex-wrap gap-1.5 min-h-[1.75rem]">
          {(tags ?? []).length === 0 && (
            <span className="text-xs text-muted-foreground italic">No tags yet.</span>
          )}
          {(tags ?? []).map((t) => (
            <Badge key={t} variant="secondary" className="gap-1 pr-1">
              <span>{t}</span>
              <button
                onClick={() => apply("remove", t)}
                disabled={update.isPending}
                className="hover:text-destructive"
                title="Remove tag"
              >
                <X className="w-3 h-3" />
              </button>
            </Badge>
          ))}
        </div>
        <form
          className="flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            const v = draft.trim();
            if (!v) return;
            apply("add", v);
          }}
        >
          <Input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="add a tag…"
            className="h-8 text-xs"
            disabled={update.isPending}
          />
          <Button type="submit" size="sm" disabled={update.isPending || !draft.trim()}>
            {update.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : "Add"}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}

// ─── Tweak-and-regenerate dialog (Phase 11) ────────────────────────────
//
// Edit the parent run's parsed_design_data in a JSON textarea, then
// regenerate against the edited copy. Useful for parser-fix validation
// — tester tweaks a missing field, regens, compares the child against
// the parent in the run-diff page to see exactly what the change moved.

function TweakRegenDialog({
  open,
  onOpenChange,
  designData,
  running,
  onSubmit,
}: {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  designData: Record<string, any>;
  running: boolean;
  onSubmit: (d: Record<string, any>) => void;
}) {
  const initial = useMemo(
    () => JSON.stringify(designData ?? {}, null, 2),
    [designData],
  );
  const [draft, setDraft] = useState(initial);
  const [parseError, setParseError] = useState<string | null>(null);

  // Re-seed when a different run is opened.
  useEffect(() => {
    setDraft(initial);
    setParseError(null);
  }, [initial]);

  const handleSubmit = () => {
    try {
      const parsed = JSON.parse(draft);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        setParseError("design_data must be a JSON object (not an array or scalar).");
        return;
      }
      setParseError(null);
      onSubmit(parsed);
    } catch (e: any) {
      setParseError(e?.message ?? "Invalid JSON");
    }
  };

  const handleResetToOriginal = () => {
    setDraft(initial);
    setParseError(null);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-base">
            <Pencil className="w-4 h-4" />
            Tweak design_data and regenerate
          </DialogTitle>
          <DialogDescription className="text-xs">
            Edit the parsed RUP envelope inline, then regenerate. Useful for
            simulating a parser fix — adjust the field by hand, regen, and
            compare the child run against this parent to see what moved.
            The edited blob is sent verbatim to{" "}
            <span className="font-mono">/regenerate</span>.
          </DialogDescription>
        </DialogHeader>
        <div className="flex-1 min-h-0 overflow-hidden">
          <Textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            spellCheck={false}
            className="h-[50vh] font-mono text-[11px] leading-snug"
          />
        </div>
        {parseError && (
          <p className="text-xs text-destructive flex items-start gap-2">
            <XCircle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
            {parseError}
          </p>
        )}
        <DialogFooter className="gap-2">
          <Button variant="outline" size="sm" onClick={handleResetToOriginal} disabled={running}>
            Reset to original
          </Button>
          <Button size="sm" onClick={handleSubmit} disabled={running}>
            {running ? (
              <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
            ) : (
              <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
            )}
            Regenerate with edits
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// ─── Compare-with-sample card ──────────────────────────────────────────

function CompareCard({ runId }: { runId: number }) {
  const { toast } = useToast();
  const compare = useCompareBomRunFile();
  const [report, setReport] = useState<CompareReport | null>(null);

  // Reset stale results when the user navigates between runs.
  useEffect(() => {
    setReport(null);
  }, [runId]);

  const handleFile = (file: File) => {
    compare.mutate(
      { id: runId, file },
      {
        onSuccess: (r) => {
          setReport(r);
          toast({
            title: "Comparison complete",
            description: `${(r.metrics.sku_match_rate * 100).toFixed(1)}% SKU match — ${r.metrics.matched}/${r.metrics.sample_count} matched.`,
          });
        },
        onError: (err) => {
          toast({
            title: "Comparison failed",
            description: err?.error ?? "unknown error",
            variant: "destructive",
          });
        },
      },
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm flex items-center gap-2">
          <FileSpreadsheet className="w-4 h-4 text-muted-foreground" />
          Compare with sample BOM
        </CardTitle>
        <CardDescription className="text-xs">
          Upload a contractor's reference BOM (.xls / .xlsx). Pairs SKUs
          (case-insensitive) and falls back to description-substring matching
          for AI-only lines without a SKU.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="flex items-center gap-2">
          <label className="inline-flex items-center gap-2 px-3 py-1.5 text-xs font-medium border rounded-md hover:bg-muted cursor-pointer">
            <Upload className="w-3.5 h-3.5" />
            {compare.isPending ? "Comparing…" : "Upload sample BOM"}
            <input
              type="file"
              accept=".xls,.xlsx"
              className="hidden"
              disabled={compare.isPending}
              onChange={(e) => {
                const f = e.target.files?.[0];
                if (f) handleFile(f);
                // Reset so the same file can be re-picked later
                e.target.value = "";
              }}
            />
          </label>
          {compare.isPending && <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />}
          {report && (
            <span className="text-xs text-muted-foreground truncate">
              {report.sample_filename}
            </span>
          )}
        </div>

        {report && <ComparisonReportView report={report} />}
      </CardContent>
    </Card>
  );
}

function ComparisonReportView({ report }: { report: CompareReport }) {
  const m = report.metrics;
  const matchPct = m.sku_match_rate * 100;
  const strictPct = m.sku_match_with_qty_rate * 100;
  const headlineColor =
    matchPct >= 80 ? "text-emerald-600" :
    matchPct >= 50 ? "text-amber-600" :
    "text-rose-600";

  // Limit per-status sections for readability — full payload in raw inspector.
  const byStatus = useMemo(() => {
    const out: Record<string, typeof report.lines> = { matched: [], qty_mismatch: [], missing: [], extra: [] };
    for (const l of report.lines) (out[l.status] ??= []).push(l);
    return out;
  }, [report.lines]);

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <CompareStat label="Sample rows" value={String(m.sample_count)} />
        <CompareStat label="Generated rows" value={String(m.generated_count)} />
        <CompareStat
          label="SKU match"
          value={`${matchPct.toFixed(1)}%`}
          sub={`${m.matched + m.qty_mismatch}/${m.sample_count}`}
          color={headlineColor}
        />
        <CompareStat
          label="Strict (qty too)"
          value={`${strictPct.toFixed(1)}%`}
          sub={`${m.matched}/${m.sample_count}`}
        />
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
        <BucketBadge label="Matched"      n={m.matched}      tone="emerald" />
        <BucketBadge label="Qty mismatch" n={m.qty_mismatch} tone="amber" />
        <BucketBadge label="Missing"      n={m.missing}      tone="rose" />
        <BucketBadge label="Extra"        n={m.extra}        tone="amber" />
      </div>

      {(["missing", "qty_mismatch", "extra", "matched"] as const).map((status) => {
        const rows = byStatus[status];
        if (!rows || rows.length === 0) return null;
        return (
          <details key={status} className="border rounded-md" open={status === "missing"}>
            <summary className="cursor-pointer px-3 py-2 text-xs font-medium flex items-center justify-between">
              <span className="capitalize">{status.replace("_", " ")}</span>
              <Badge variant="outline" className="text-[10px]">{rows.length}</Badge>
            </summary>
            <div className="overflow-x-auto border-t">
              <table className="w-full text-[11px]">
                <thead>
                  <tr className="bg-muted/30 text-muted-foreground">
                    <th className="text-left px-3 py-1.5 font-medium">SKU</th>
                    <th className="text-left px-3 py-1.5 font-medium">Description</th>
                    <th className="text-right px-3 py-1.5 font-medium">Sample qty</th>
                    <th className="text-right px-3 py-1.5 font-medium">Gen qty</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/40">
                  {rows.slice(0, 50).map((l, i) => (
                    <tr key={i} className="hover:bg-muted/20">
                      <td className="px-3 py-1 font-mono">{l.sku ?? "—"}</td>
                      <td className="px-3 py-1 truncate max-w-[420px]">{l.description ?? "—"}</td>
                      <td className="px-3 py-1 text-right">{l.sample_qty ?? "—"}</td>
                      <td className="px-3 py-1 text-right">{l.generated_qty ?? "—"}</td>
                    </tr>
                  ))}
                  {rows.length > 50 && (
                    <tr>
                      <td colSpan={4} className="px-3 py-2 text-center text-muted-foreground italic">
                        … {rows.length - 50} more rows omitted
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </details>
        );
      })}
    </div>
  );
}

function CompareStat({ label, value, sub, color }: { label: string; value: string; sub?: string; color?: string }) {
  return (
    <div className="border rounded-md p-2.5">
      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
      <p className={cn("text-lg font-bold leading-tight", color)}>{value}</p>
      {sub && <p className="text-[10px] text-muted-foreground">{sub}</p>}
    </div>
  );
}

function BucketBadge({ label, n, tone }: { label: string; n: number; tone: "emerald" | "rose" | "amber" }) {
  const cls =
    tone === "emerald" ? "border-emerald-500/30 text-emerald-700 dark:text-emerald-400" :
    tone === "rose"    ? "border-rose-500/30 text-rose-700 dark:text-rose-400" :
                         "border-amber-500/30 text-amber-700 dark:text-amber-400";
  return (
    <div className={cn("border rounded px-2 py-1 flex items-center justify-between", cls)}>
      <span className="text-[10px] uppercase tracking-wide">{label}</span>
      <span className="text-sm font-bold">{n}</span>
    </div>
  );
}

// ─── Helpers ───────────────────────────────────────────────────────────

function Stat({
  label,
  value,
  icon: Icon,
}: {
  label: string;
  value: React.ReactNode;
  icon?: typeof Clock;
}) {
  return (
    <div>
      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        {label}
      </p>
      <div className="font-medium truncate flex items-center gap-1 mt-0.5">
        {Icon && <Icon className="w-3 h-3 text-muted-foreground" />}
        {value}
      </div>
    </div>
  );
}

function RawPayload({ label, payload }: { label: string; payload: unknown }) {
  const [open, setOpen] = useState(false);
  if (payload == null) return null;
  return (
    <Card>
      <CardHeader
        className="py-3 cursor-pointer select-none"
        onClick={() => setOpen((v) => !v)}
      >
        <CardTitle className="text-xs font-mono flex items-center justify-between">
          <span>{label}</span>
          <span className="text-muted-foreground text-[10px]">
            {open ? "click to hide" : "click to inspect"}
          </span>
        </CardTitle>
      </CardHeader>
      {open && (
        <CardContent className="pt-0">
          <pre className="text-[11px] bg-muted/40 rounded p-3 overflow-x-auto max-h-[400px]">
            {JSON.stringify(payload, null, 2)}
          </pre>
        </CardContent>
      )}
    </Card>
  );
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  try {
    const d = new Date(iso);
    return d.toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}
